### ISSUE TITLE
Plugin conflicts with Brewery plugin

### ISSUE THREAD

**Issue by Zobody** [fof1092/TimeVote#3]
Link to Brewery plugin's github page: https://github.com/DieReicheErethons/Brewery

Link to Spigot page: https://www.spigotmc.org/resources/brewery.3082/

Basically, when they're both together, time speed up to day and night passing multiple times a second.

**Comment by fof1092** [comment]
Ehm what?

**Comment by Zobody** [comment]
When you have both plugins, time speeds up.
